---
- name: OpenStack
  hosts: localhost
  vars_files:
    - variables/openstack.yaml
  gather_facts: true
  roles:
    - role: openstack-prep
    - role: openstack-volume
    - role: openstack-security-group
    - role: openstack-instance

- name: Mastodon
  hosts: mastodon_servers
  vars_files:
    - variables/mastodon.yaml
  gather_facts: true
  roles:
    - role: mastodon-prep
    - role: mastodon-docker
    - role: mastodon-get-app
    - role: mastodon-mastodon
...


