version: '3'

services:
  couchdb1:
    image: couchdb:3.2.0
    restart: always
    environment:
      - NODENAME=couchdb1@node-2
      - ERL_FLAGS="-setcookie 'couchdb-cluster' -name couchdb1@node-2"
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    volumes:
      - /home/ubuntu/Documents/couchdb_data:/opt/couchdb/data
    ports:
      - 5984:5984
    networks:
      couchdb_cluster:
        ipv4_address: 172.26.135.104

  couchdb2:
    image: couchdb:3.2.0
    restart: always
    environment:
      - NODENAME=couchdb2@node-3
      - ERL_FLAGS="-setcookie 'couchdb-cluster' -name couchdb2@node-3"
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    volumes:
      - /home/ubuntu/Documents/couchdb_data:/opt/couchdb/data
    ports:
      - 5985:5984
    networks:
      couchdb_cluster:
        ipv4_address: 172.26.135.105

  couchdb3:
    image: couchdb:3.2.0
    restart: always
    environment:
      - NODENAME=couchdb3@node-4
      - ERL_FLAGS="-setcookie 'couchdb-cluster' -name couchdb3@node-4"
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    volumes:
      - /home/ubuntu/Documents/couchdb_data:/opt/couchdb/data
    ports:
      - 5986:5984
    networks:
      couchdb_cluster:
        ipv4_address: 172.26.135.145

networks:
  couchdb_cluster:
    driver: bridge
    ipam:
      config:
        - subnet: 172.26.0.0/16
