# Common vars
availability_zone: melbourne-qh2-uom
instance_image: bbaf16f8-2484-48d7-b455-42209cc4b8d2
instance_key_name: cloud_key
instance_flavor: uom.mse.2c9g
instance_network: qh2-uom-internal
# security_group: db_server

# Volume
volumes:
  - name: node-1-data
    size: 100
  - name: node-2-data
    size: 100
  # - name: node-3-data
  #   size: 100

# Defines a list of instances
instances:
  - name: node-1
    volumes: ["node-1-data"]
  - name: node-2
    volumes: ["node-2-data"]
