---
- name: Create instances
  openstack.cloud.server:
    name: "{{ item.name }}" 
    auto_floating_ip: false 
    availability_zone: "{{ availability_zone }}"
    flavor: "{{ item.flavor }}"
    image: "{{ image }}" 
    key_name: "{{ key_pair }}" 
    network: "{{ network }}"    
    security_groups: "{{ item.security_groups }}" 
    timeout: 600
    volumes: "{{ item.volumes }}" 
    state: present
    wait: true 
  loop: "{{ instances }}"
  register: os_instance

- name: Print out debugging information
  ansible.builtin.debug:
    msg: "Instance {{ item.server.name }} has been created. IP address is {{ item.server.accessIPv4 }}"
  loop: "{{ os_instance.results }}"
  when: item.server is defined

- name: Wait for connection
  ansible.builtin.wait_for:
    host: "{{ item.server.accessIPv4 }}"
    port: 22
    timeout: 120
    search_regex: OpenSSH
  loop: "{{ os_instance.results }}"
  when: item.server is defined

- name: Add hosts to Ansible in-memory inventory
  ansible.builtin.add_host:
    name: "{{ item.server.accessIPv4 }}" 
    groups: mastodon_servers
  loop: "{{ os_instance.results }}"
  when: item.server is defined
...

