---
device: /dev/vdb
mountpoint: /var/lib/docker/volumes

docker_volume:
  name: couchdb
  type: volume
  target: /opt/couchdb/data

docker_container:
  name: couchdb
  base_image: ibmcom/couchdb3:3.2.1
  env:
    user: admin
    password: password
    secret: "a192aeb9904e6590849337933b000c99"
  ports: ["5984:5984", "4369:4369", "9100:9100"]


