- name: Create a directory for the application
  become: true
  ansible.builtin.file:
    path: /var/lib/docker/volumes/repo
    recurse: true
    mode: 0700
    state: directory

- name: Get Mastodon client
  ansible.builtin.git:
    repo: "https://github.com/ss2333030/COMP90024_assignment_2"
    dest: /var/lib/docker/volumes/repo

- name: Create a volume for the application
  become: true
  community.docker.docker_volume:
    name: mastodon
    state: present
  register: volume_result

- name: Print out debugging information
  ansible.builtin.debug:
    msg: "{{ volume_result }}"

- name: Print out debugging information
  ansible.builtin.debug:
    msg: "{{ansible_nodename}} {{ ansible_default_ipv4.address | string }} {{ groups['db_servers'] | difference([ansible_default_ipv4.address]) }} {{ groups['db_servers'] | length }}" 

- name: Build image and with build args
  community.docker.docker_image:
    name: mastodon
    build:
      path: /var/lib/docker/volumes/repo/mastodon
    source: build
    sttate: present


- name: Set up a Mastodon client container
  become: true
  community.docker.docker_container:
    name: mastodon
    image: mastodon
    mounts:
      - type: volume
        target: /repo
        source: mastodon
    working_dir: /repo/mastodon
    detach: true
    state: started
