---
- name: Create a security group for database servers
  openstack.cloud.security_group:
    name: "{{ db_server_security_group.name }}"
    description: "{{ db_server_security_group.description }}"
    state: present

- name: Create a list of security group names
  ansible.builtin.set_fact:
    sg_names: "{{ sg_names|default([]) + [ db_server_security_group.name ] }}"

- name: Print out debugging information
  ansible.builtin.debug:
    msg: "Security group(s) {{ sg_names }} have been created."

- name: Add security group rules to the security groups
  openstack.cloud.security_group_rule:
    security_group: "{{ db_server_security_group.name }}"
    protocol: "{{ item.protocol }}"
    port_range_min: "{{ item.port_range_min }}"
    port_range_max: "{{ item.port_range_max }}"
    remote_ip_prefix: "{{ item.remote_ip_prefix }}"
    state: present
  loop: "{{ db_server_security_group.rules }}"