---
# Create volumes
- name: Create volumes
  openstack.cloud.volume:
    display_name: "{{ item.name }}"
    size: "{{ item.size }}"
    availability_zone: "{{ availability_zone }}"
    wait: true
    timeout: 600
    state: present
  loop: "{{ volumes }}"
  register: os_vol

# Get a list of volume Ids from the return value of os_volume
- name: Create a list of volume Ids
  ansible.builtin.set_fact:
    os_vol_ids: "{{ os_vol_ids|default([]) + [ item.volume.id ] }}"
  loop: "{{ os_vol.results }}"

- ansible.builtin.debug:
    msg: "Volume {{ os_vol_ids }} has been created."

- name: Install dependencies
  become: true
  ansible.builtin.apt:
    name: ["e2fsprogs"]   # package for managing ext4 filesystems
    state: latest
    install_recommends: false
    update_cache: true

- name: Make file system
  become: true
  community.general.filesystem:
    fstype: ext4
    dev: "{{ volume.device }}"
    state: present

- name: Mount device
  become: true
  ansible.posix.mount:
    path: "{{ volume.mountpoint }}"
    src: "{{ volume.device }}"
    fstype: ext4
    state: mounted

