---
# - name: OpenStack
#   hosts: localhost
#   vars_files:
#     - vars/openstack.yaml
#   gather_facts: true
#   roles:
#     # - role: openstack-common
#     # - role: openstack-volume
#     # - role: openstack-security-group
#     - role: openstack-instance

- name: Mastodon
  hosts: mastodon_servers
  gather_facts: true
  roles:
    - role: mastodon-common
    - role: mastodon-docker
    - role: mastodon-mastodon
...


