---
- name: OpenStack
  hosts: localhost
  vars_files:
    - variables/openstack.yaml
  gather_facts: true
  roles:
    - role: openstack-prep
    - role: openstack-volume
    - role: openstack-security-group
    - role: openstack-instance

- name: Mastodon
  hosts: mastodon_servers
  vars_files:
    - variables/backend.yaml
  gather_facts: true
  roles:
    - role: backend-prep
    - role: backend-docker
    - role: backend-get-app
    - role: backend-backend
...


