---
# Create security groups
- name: Create security groups
  openstack.cloud.security_group:
    name: "{{ db_server_security_group.name }}"
    description: "{{ db_server_security_group.description }}"
    state: present

- name: Create a list of security group names
  ansible.builtin.set_fact:
    sg_name: "{{ db_server_security_group.name }}"

- ansible.builtin.debug:
    msg: "Security group {{ sg_name }} have been created."

# Create security group rules
- name: Create security group rules
  openstack.cloud.security_group_rule:
    security_group: "{{ db_server_security_group.name }}"
    protocol: "{{ item.protocol }}"
    port_range_min: "{{ item.port_range_min }}"
    port_range_max: "{{ item.port_range_max }}"
    remote_ip_prefix: "{{ item.remote_ip_prefix }}"
    state: present
  loop: "{{ db_server_security_group.rules }}"
