---
- name: Create volumes
  openstack.cloud.volume:
    display_name: "{{ item.name }}"
    size: "{{ item.size }}"
    availability_zone: "{{ availability_zone }}"
    wait: true
    timeout: 600
    state: present
  loop: "{{ volumes }}"
  register: os_vol

- name: Create a list of volume Ids
  ansible.builtin.set_fact:
    os_vol_ids: "{{ os_vol_ids|default([]) + [ item.volume.id ] }}"
  loop: "{{ os_vol.results }}"

- name: Print out debugging information
  ansible.builtin.debug:
    msg: "Volume {{ os_vol_ids }} has been created."


